[package]
name = "initializer"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-client = {workspace = true}
solana-sdk = {workspace = true}
solana-program = {workspace = true}
rome-evm = {path = "../program"}
