chain_id: 1001
start_slot: 0
solana:
  rpc_url: "http://solana:8899"
  commitment: "confirmed"
program_keypair: "/opt/ci/rome-keypair.json"
payer_keypair: "/opt/ci/proxy/upgrade-authority-keypair.json"
number_holders: 256
proxy_host: "0.0.0.0:9090"


