chain_id: 1001
solana_url: "http://solana:8899"
commitment_level: "confirmed"
program_id_keypair: "/opt/ci/rome-keypair.json"
payer_keypair: "/opt/ci/proxy/rome-owner-keypair.json"
log: "/var/log/rhea/rhea.log"
host: "0.0.0.0:9090"
number_holders: 256
start_slot: 0

