services:
  solana:
    container_name: solana
    image: romelabs/rome-evm:${REF_NAME:-latest}
    environment:
      RUST_LOG: solana_runtime::system_instruction_processor=debug,solana_runtime::message_processor=debug,solana_bpf_loader=debug,solana_rbpf=debug
    hostname: solana
    ports:
      - 8899:8899
      - 9900:9900
      - 8900:8900
      - 8003:8003/udp
    expose:
      - "8899"
      - "9900"
      - "8900"
      - "8001"
      - "8001-8009/udp"
    networks:
      - net
    healthcheck:
      test: [ CMD-SHELL, "solana cluster-version -u http://solana:8899" ]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 10s

  tests:
    container_name: tests
    image: romelabs/tests:${TESTS_REF_NAME:-latest}
    environment:
      TEST_NAME: evm
    hostname: tests
    networks:
      - net
    depends_on:
      solana:
        condition: service_started

  proxy:
    container_name: proxy
    image: romelabs/rome-apps:${ROME_APPS:-latest}
    hostname: proxy
    environment:
      SERVICE_NAME: proxy
      PROXY_CONFIG: /opt/cfg/proxy-config.yml
    volumes:
      - ./keys:/opt/keys
      - ./cfg:/opt/cfg
    ports:
      - 9090:9090
    networks:
      - net
    depends_on:
      solana:
        condition: service_healthy
    healthcheck:
      test: [
        CMD-SHELL,
        "curl --location 'proxy:9090' --header 'Content-Type: application/json' --data '{\"jsonrpc\":\"2.0\",\"method\":\"eth_blockNumber\",\"params\":[],\"id\":83}'"
      ]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 10s

  uniswap-v2-core:
    container_name: uniswap
    image: romelabs/uniswap-v2-core:latest
    environment:
      NETWORK: proxy
      CHAIN_ID: 1001
    depends_on:
      proxy:
        condition: service_started
    networks:
      - net
    entrypoint: yarn test

networks:
  net:
