services:
  solana:
    container_name: solana
    image: romelabs/rome-evm:${REF_NAME:-latest}
    environment:
      RUST_LOG: solana_runtime::system_instruction_processor=debug,solana_runtime::message_processor=debug,solana_bpf_loader=debug,solana_rbpf=debug
    hostname: solana
    ports:
      - 8899:8899
      - 9900:9900
      - 8900:8900
      - 8003:8003/udp
    expose:
      - "8899"
      - "9900"
      - "8900"
      - "8001"
      - "8001-8009/udp"
    networks:
      - net
    healthcheck:
      test: [ CMD-SHELL, "solana cluster-version -u http://solana:8899" ]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 10s

  tests:
    container_name: tests
    image: romelabs/tests:${TESTS_REF_NAME:-latest}
    entrypoint: /bin/bash -c "/bin/bash -c \"$${@}\""
    command: >
      /bin/sh -c
      "
      sleep 10 &&
      /opt/bin/solana-keygen new --no-bip39-passphrase --silent;
      /opt/bin/solana -u http://solana:8899 -v airdrop 1000 /opt/ci/keys/registry-authority-keypair.json;
      /opt/bin/solana -u http://solana:8899 -v airdrop 10000000 /opt/ci/keys/test-account-keypair.json;
      /opt/bin/evm
      "
    environment:
      TEST_NAME: evm
      GETH_URL: http://localhost:8545
      PROXY_URL: http://localhost:9090
    hostname: tests
    networks:
      - net
    depends_on:
      solana:
        condition: service_started

networks:
  net:
