name: ci_pipeline

on:
  push:
  workflow_dispatch:

env:
  REF_NAME: ${{github.ref_name}}
  TESTS_REF_NAME: main 
  ROME_SDK_REF_NAME: main 
  ROME_APPS: main

permissions:
  contents: read
jobs:
  build:
    runs-on:
      labels: ubuntu-22.04-2core-8gb-75
    steps:
      - name: Install Compose
        uses: ndeloof/install-compose-action@v0.0.1
        with:
          version: v2.1.0 # defaults to 'latest'
          legacy: true    # will also install in PATH as `docker-compose`

      - name: Check Docker Compose version
        run: docker-compose --version

      - name: 'Checkout rome-sdk repository'
        uses: actions/checkout@master
        with:
          repository: rome-labs/rome-sdk
          path: rome-sdk
          ref: ${{env.ROME_SDK_REF_NAME}}
          token: ${{ secrets.GIT_ROLLUP_TOKEN }}

      - name: 'Checkout rome-apps repository'
        uses: actions/checkout@master
        with:
          repository: rome-labs/rome-apps
          path: rome-apps
          ref: ${{env.ROME_APPS}}
          token: ${{ secrets.GIT_ROLLUP_TOKEN }}

      - name: 'Checkout tests repository'
        uses: actions/checkout@master
        with:
          repository: rome-labs/tests
          path: tests
          ref: ${{env.TESTS_REF_NAME}}
          token: ${{ secrets.GIT_ROLLUP_TOKEN }}

      - name: 'Checkout rome-evm repository'
        uses: actions/checkout@v4
        with:
          path: rome-evm
          token: ${{ secrets.GIT_ROLLUP_TOKEN }}

      - name: 'Login to Docker Hub'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: 'Build rome-evm builder'
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: true
          file: rome-evm/ci/Builder.Dockerfile
          tags: romelabs/rome-evm-builder:${{env.REF_NAME}}
          labels: romelabs/rome-evm-builder:${{env.REF_NAME}}

      - name: 'Build test validator'
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: true
          file: rome-evm/ci/TestValidator.Dockerfile
          tags: romelabs/test-validator:${{env.REF_NAME}}
          labels: romelabs/test-validator:${{env.REF_NAME}}
          build-args: |
            "BUILDER_REF_NAME=${{env.REF_NAME}}"
            "IMAGE_NAME=romelabs/rome-evm-builder"

      - name: 'Build tests image'
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: false
          file: tests/ci/Dockerfile
          tags: romelabs/tests:${{env.TESTS_REF_NAME}}
          labels: romelabs/tests:${{env.TESTS_REF_NAME}}

      - name: 'Up tests'
        run: docker-compose -f rome-evm/ci/docker-compose.yml up tests

      - name: 'Build rome-apps image'
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: false
          file: rome-apps/docker/Dockerfile
          tags: romelabs/rome-apps:${{env.ROME_APPS}}
          labels: romelabs/rome-apps:${{env.ROME_APPS}}

      - name: 'Up Uniswap-v2-core tests'
        run: docker-compose -f rome-evm/ci/docker-compose.yml up uniswap-v2-core

      - name: 'Dump docker logs'
        uses: jwalton/gh-docker-logs@v2
        with:
          dest: './logs'

      - name: 'Tar logs'
        run: tar cvzf ./logs.tgz ./logs
      - name: Upload logs to GitHub
        uses: actions/upload-artifact@master
        with:
          name: logs.tgz
          path: ./logs.tgz

      - name: 'Parse tests results'
        run: |
          if grep "FAIL" ./logs/tests.log
          then
            echo "Tests finished with errors";
            exit 1;
          else
            echo "Tests completed successfully";
          fi

      - name: 'Down docker-compose'
        run: docker-compose -f rome-evm/ci/docker-compose.yml down --rmi all -v

      - name: 'Set latest tag'
        if: |
          ( github.ref_name == 'main' )
        run: |
          
          docker pull romelabs/rome-evm-builder:${REF_NAME}
          docker tag romelabs/rome-evm-builder:${REF_NAME} romelabs/rome-evm-builder:latest
          docker push romelabs/rome-evm-builder:latest
          
          docker pull romelabs/test-validator:${REF_NAME}
          docker tag romelabs/test-validator:${REF_NAME} romelabs/test-validator:latest
          docker push romelabs/test-validator:latest
      
